### ISSUE TITLE
Error using standalone file in dist

### ISSUE THREAD

**Issue by diffsky** [matthewmueller/date#88]
When using https://github.com/matthewmueller/date/blob/master/dist/date.js directly in the browser I get the following error:

```
date.js:18 Uncaught Error: Failed to require "./norm" from "date/lib/parser.js"
    at require (date.js:18)
    at localRequire (date.js:171)
    at date.min.js:980
    at require (date.js:35)
    at localRequire (date.js:171)
    at date.min.js:707
    at require (date.js:35)
    at date.min.js:1633
    at date.min.js:1634
```

That file at the previous commit sha (https://github.com/matthewmueller/date/blob/8fe7afbfb20d72e36f0a7864bd71bd1598401880/dist/date.js) does not have the error and works fine in the browser.

**Comment by matthewmueller** [comment]
Yikes! Good catch and also great to hear from you @diffsky! 😬

Just switched date over from the defunct component build system to browserify. the `dist/` files should be working again in 0.3.3!

**Comment by diffsky** [comment]
Sweet, thanks @matthewmueller and :wave: hope you're doing great

**Comment by diffsky** [comment]
Hey @matthewmueller, FYI just checked the minified file and it's empty: https://github.com/matthewmueller/date/blob/master/dist/date.min.js
